# Generated by Django 5.2.6 on 2025-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasbasico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Lista de beneficios generados por IA (formato JSON)', null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Descripción breve generada por IA (1-2 líneas)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion_generada_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se generó la descripción con IA', null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Descripción detallada generada por IA', null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='palabras_clave',
            field=models.CharField(blank=True, help_text='Keywords SEO generadas por IA (separadas por comas)', max_length=500, null=True),
        ),
    ]
