# Generated by Django 6.0 on 2025-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasbasico', '0002_productos_beneficios_productos_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
