# Generated by Django 5.2.6 on 2025-12-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasbasico', '0003_productos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
