# Generated by Django 5.2 on 2025-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
