# Generated by Django 5.2 on 2025-09-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Comuna',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Rut',
            new_name='rut',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
